highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jekyller.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Ricardo Oliveira's Resume
name: Ricardo Martinelli de Oliveira
email: ricardo.martinelli.oliveira@gmail.com
email_full: mailto:ricardo.martinelli.oliviera@gmail.com
website: rimolive.github.io/vitae
website_full: https://rimolive.github.io/vitae
github: rimolive
twitter: rimolive
twitter: rmartinelli
tel: +55 11970696531
tel_full: tel:+5511970696531
google_maps: 'https://www.google.com/maps/place/Rua+Vergueiro,+7133+-+Vila+Nair,+S%C3%A3o+Paulo+-+SP,+04289-125/@-23.6082997,-46.6157452,17z/data=!3m1!4b1!4m5!3m4!1s0x94ce5ba2b9fa0c41:0xf4d8b7c73032b2d6!8m2!3d-23.6082997!4d-46.6135565'
address:
  street: Rua Vergueiro, 7133 Apt 30
  postcode: 04273-100
  city: Sao Paulo
  country: Brazil
google_analytics: UA-79558076-2

# needed for travis-ci build
exclude: [vendor]
